baseurl = "https://blog.jolexa.net/"
languageCode = "en-us"
title = "Home of Jeremy Olexa"
theme = "vienna"
Paginate = 5
category = "categories"
copyright = "&copy; Copyright 2008-2015 | jolexa.net"

[params]
	twitter = "jolexa"
	github = "jolexa"
	keybase = "jolexa"
	author = "Jeremy Olexa"
	contact = "mailto:info@jolexa.net?subject='Inquiry from blog'"
	bio = "Random stuff that I write and make public to the interwebs. I am a tech enthusiast, so some posts are about tech/software. However, as of late, most will be about traveling. I hope you enjoy and find something useful."
	recentPosts = true
	recentPostDisplayCount = 5
	categories = true
	disqus = "jolexa"
